apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/autoscaler
      chart: cluster-autoscaler
      targetRevision: 9.59.0
      helm:
        valueFiles:
          - $values/infra/platform/apps/cluster-autoscaler/values.yaml
    - repoURL: https://github.com/AndreRosaLopes/eks_on_AWS_OpenSource
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
